spring.application.name=agri-management
spring.datasource.url=jdbc:mysql://localhost:3306/agri_db
spring.datasource.username=root
spring.datasource.password=231205

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
